// Tienda_AngularJS/src/app/barra-superior/barra-superior.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ClienteTiendaService } from '../cliente-tienda.service';
import { ConexionBDService } from '../conexion-bd.service';

@Component({
  selector: 'barra-superior',
  templateUrl: './barra-superior.component.html',
  styleUrls: ['./barra-superior.component.css']
})
export class BarraSuperiorComponent {

  nombreIconoSesion:string = "";

  constructor(
    private clienteTiendaService:ClienteTiendaService,
    private conexionBDService:ConexionBDService,
    private router:Router
  ) {}

  /*Cierra la sesión en el servidor. Funcione o no regresa a la página de login llamando
   a la función cambiarPagina() del servicio ClienteTiendaService */
  cerrarSesion(){
    this.conexionBDService.cerrarSesion((respuesta)=>{
      this.clienteTiendaService.cambiarPagina('');
    })
  }
}

<div class="top-bar barraSuperior">
  <div class="top-bar-left">
    <h5>Tienda Web</h5>
  </div>
  <div class="top-bar-right">
    <div class="menu barraSuperior">
      <div class="menu-item">
        <a [routerLink]="['/catalogo']">
          <i class="fi-thumbnails"></i> Catálogo
        </a>
      </div>
      <div class="menu-item">
        <a [routerLink]="['/carrito']">
          <i class="fi-shopping-cart"></i> Carrito
          <div class="badge iconoNotifCarrito" *ngIf="clienteTiendaService.productosCarrito.length>0">
            {{clienteTiendaService.productosCarrito.length}}
          </div>
        </a>
      </div>
      <div class="menu-item">
        <a (click)="cerrarSesion()">
          <i [class]="clienteTiendaService.estadoLogin == 2 ? 'fi-x':'fi-home'"></i>
          {{clienteTiendaService.estadoLogin == 2 ? "Cerrar sesión" : "Login"}}
        </a>
      </div>
    </div>
  </div>
</div>
<div class="cell small-12 msjBienvenida">
  {{ clienteTiendaService.estadoLogin == 0 ? "Verificando sesión..." :
    (clienteTiendaService.estadoLogin == 1 ? "Navegando como invitado" :
    (clienteTiendaService.estadoLogin == 2 ? "Bienvenido, "+clienteTiendaService.usuarioLogueado :
    (clienteTiendaService.estadoLogin == 3 ? "Sin conexión con el servidor" : "ERROR")))
  }}
</div>

// Tienda_ReactJS/BarraSuperior.jsx
import React from 'react';
import { Link, Redirect } from 'react-router-dom';
import { TopBar, TopBarLeft, TopBarRight, Menu, MenuItem, Icon, Cell, Badge } from 'react-foundation';

import conexionBD from './conexionBD';

class BarraSuperior extends React.Component {
  constructor() {
    super();
  }

  render(){
    return(
      <div>
        <TopBar className="barraSuperior">
          <TopBarLeft>
            <h5>Tienda Web</h5>
          </TopBarLeft>
          <TopBarRight>
            <Menu className="barraSuperior">
              <MenuItem>
                <Link to="/catalogo">
                  <Icon name="fi-thumbnails"></Icon>Catálogo
                </Link>
              </MenuItem>
              <MenuItem>
                <Link to="/carrito">
                  <Icon name="fi-shopping-cart"></Icon>Carrito
                  {
                    this.props.cantProdsCarrito == 0 ? null :
                    <Badge className="iconoNotifCarrito">{this.props.cantProdsCarrito}</Badge>
                  }
                </Link>
              </MenuItem>
              <MenuItem>
                <a onClick={this.cerrarSesion.bind(this)}>
                  <Icon name={this.props.estadoLogin == 2 ? "fi-x":"fi-home"}/>
                  {this.props.estadoLogin == 2 ? "Cerrar sesión" : "Login"}
                </a>
              </MenuItem>
            </Menu>
          </TopBarRight>
        </TopBar>
        <Cell small={12} className="msjBienvenida">
          { this.props.estadoLogin == 0 ? "Verificando sesión..." :
           (this.props.estadoLogin == 1 ? "Navegando como invitado" :
           (this.props.estadoLogin == 2 ? "Bienvenido, "+this.props.usuarioLogueado :
           (this.props.estadoLogin == 3 ? "Sin conexión con el servidor" : "ERROR")))}
        </Cell>
      </div>
    );
  }

  /*Cierra la sesión en el servidor. Funcione o no regresa a la página de login llamando
   a la función del componente Login pasada por props */
  cerrarSesion(){
    conexionBD.cerrarSesion((respuesta)=>{
      this.props.irALogin();
    });
  }
}

export default BarraSuperior;
