// Tienda_AngularJS/src/app/display-detallado-producto/display-detallado-producto.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, ParamMap } from '@angular/router';
import { ConexionBDService } from '../conexion-bd.service';
import { ClienteTiendaService } from '../cliente-tienda.service';

@Component({
  selector: 'display-detallado-producto',
  templateUrl: './display-detallado-producto.component.html',
  styleUrls: ['./display-detallado-producto.component.css']
})
export class DisplayDetalladoProductoComponent implements OnInit{
  producto = null;

  constructor(
    private route:ActivatedRoute,
    private conexionBDService:ConexionBDService,
    private clienteTiendaService:ClienteTiendaService
  ) { }

  ngOnInit() {
    /* Obtenemos la id del producto desde la url.
      Los datos de la url están contenidos dentro del route (ActivatedRoute),
      componente de angular router encargado de manipular la barra de direcciones. */
    let id = this.route.snapshot.paramMap.get('idProducto');
    //Cargamos el detalle del producto, a partir de la id pasada a través de la URL (!)
    //Ej: localhost:8080/producto/5cc50e5cfa0df01d94ac951b
    this.cargarProducto(id);
  }

  //Obtiene los datos del producto del servidor
  cargarProducto(idProducto){
    this.conexionBDService.obtenerDetalleProducto(idProducto, (respuesta)=>{
      if(respuesta.exito){
        this.producto = respuesta.producto;
      } else {
        console.log("Error al conectar con el servidor: "+respuesta.msjError);
        console.log(respuesta.error);
      }
    })
  }

  //Regresa al catálogo
  clickAtras(){
    this.clienteTiendaService.cambiarPagina("/catalogo");
  }
}

<div class="grid-x">
  <div class="cell panelPrincipal small-12">
    <div class="grid-x grid-margin-x">
      <div class="cell barraTitulo small-12">
        <h4>{{producto ? producto.nombre : "..."}}</h4>
      </div>
      <div class="cell margenInferior small-12 medium-6">
        <img [src]="producto ? 'assets/imagenesBase/'+producto.nombreArchivo : ''">
      </div>
      <div class="cell margenInferior small-12 medium-6">
        <label class="lblProducto"><b>Precio: $</b>{{producto ? producto.precio : "..."}}</label>
        <label class="lblProducto"><b>Unidades Disponibles: </b>{{producto ? producto.stock : "..."}}</label>
      </div>
      <div class="cell small-12">
        <div class="button" (click)="clickAtras()"><i class="fi-arrow-left"></i> Atrás</div>
      </div>
    </div>
  </div>
</div>

// Tienda_ReactJS/DisplayDetalladoProducto.jsx
import React from 'react';
import { Redirect } from 'react-router-dom';
import { GridContainer, Grid, Cell, Link, Icon } from 'react-foundation';

import conexionBD from './conexionBD';

import BarraSuperior from './BarraSuperior.jsx';

class DisplayDetalladoProducto extends React.Component {
  constructor(props){
    super(props);
    this.state = {
      producto:null,
      volver:false
    };

    //Cargamos el detalle del producto, a partir de la id pasada a través de la URL (!)
    //Ej: localhost:8080/producto/5cc50e5cfa0df01d94ac951b
    this.cargarProducto(props.match.params.idProducto.toLowerCase());
  }

  render(){

    if(this.state.volver){
      return(<Redirect to="/catalogo"/>);
    }

    return(
      <Grid>
        <Cell className="panelPrincipal" small={12}>
          <Grid gutters="margin">
            <Cell small={12} className="barraTitulo">
              <h4>{this.state.producto ? this.state.producto.nombre : "..."}</h4>
            </Cell>
            <Cell small={12} medium={6} className="margenInferior">
              <img src={this.state.producto ? "../imagenesBase/" + this.state.producto.nombreArchivo : ""}/>
            </Cell>
            <Cell small={12} medium={6} className="margenInferior">
              <label className="lblProducto"><b>Precio: $</b> {this.state.producto ? this.state.producto.precio : "..."}</label>
              <label className="lblProducto"><b>Unidades Disponibles: </b> {this.state.producto ? this.state.producto.stock : "..."}</label>
            </Cell>
            <Cell small={12}>
              <Link onClick={this.clickAtras.bind(this)}><Icon name="fi-arrow-left"/> Atrás</Link>
            </Cell>
          </Grid>
        </Cell>
      </Grid>
    );
  }

  //Obtiene los datos del producto del servidor
  cargarProducto(idProducto){
    let respuesta = conexionBD.obtenerDetalleProducto(idProducto, (respuesta)=>{
      if(respuesta.exito){
        this.setState({producto:respuesta.producto});
      } else {
        console.log("Error al conectar con el servidor: "+respuesta.msjError);
        console.log(respuesta.error);
      }
    });
  }

  //Regresa al catálogo
  clickAtras(){
    this.setState({volver:true});
  }
}

export default DisplayDetalladoProducto;
