// Tienda_AngularJS/src/app/login/login.component.ts
import { Component } from '@angular/core';
import { ClienteTiendaService } from '../cliente-tienda.service';
import { ConexionBDService } from '../conexion-bd.service';

@Component({
  selector: 'login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})

export class LoginComponent {
  constructor(
    private conexionBDService:ConexionBDService,
    private clienteTiendaService:ClienteTiendaService
  ){}

  validCorrecta:boolean = false;
  errorEnvio:boolean = false;
  exitoLogin:boolean = false;
  msjError:string = "";

  emailIngresado:string = "";
  contrasenaIngresada:string = "";
  emailValidCorrecta:boolean = false;
  contrasenaValidCorrecta:boolean = false;

  //Al modificarse el input del email
  cambiaEmail(email, esValido){
    this.emailIngresado = email;
    this.emailValidCorrecta = esValido;
    this.verificarValidarDatos();
  }

  //Al modificarse el input de la contraseña
  cambiaContrasena(contrasena, esValido){
    this.contrasenaIngresada = contrasena;
    this.contrasenaValidCorrecta = esValido;
    this.verificarValidarDatos();
  }

  //Validamos los campos del lado del cliente
  verificarValidarDatos(){
    if(!this.validCorrecta && this.emailValidCorrecta && this.contrasenaValidCorrecta){
      this.validCorrecta = true;
    } else if(this.validCorrecta && (!this.emailValidCorrecta || !this.contrasenaValidCorrecta)){
      this.validCorrecta = false;
    }
  }
  
  //Prueba a hacer login con el email y la contraseña ingresada enviando los datos al servidor.
  intentarLogin(callback){
    let email = this.emailIngresado;
    let contrasena = this.contrasenaIngresada;

    this.conexionBDService.intentarLogin(email, contrasena, (respuesta) => {
      callback(respuesta);
    });
  }

  clickIngresar(event){
    event.preventDefault();
    this.intentarLogin((resultado) => {
      if(resultado.exito){
        console.log("Usuario "+this.emailIngresado+" logueado");
        this.exitoLogin = true;
        this.errorEnvio = false;
        this.clienteTiendaService.cambiarPagina("/catalogo");
      } else {
        if(this.msjError == resultado.msjError){
          resultado.msjError = "*** "+resultado.msjError+" ***";
        }
        if(resultado.error){
          console.log(resultado.error);
        }
        this.errorEnvio = true;
        this.msjError = resultado.msjError;
      }
    });
  }

}

<div class="login">
  <div class="fondo loginFondo"></div>

  <div class="grid-container fluid cubrirAltura">
    <div class="grid-x align-middle cubrirAltura">
      <div class="cell small-8 medium-6 large-4 small-offset-2 medium-offset-3 large-offset-4">

        <h3 class="tituloLogin">Inicia Sesión</h3>

        <form>
          <form-input #email [texto]="'Correo electrónico'" [tipo]="'email'"
            [placeholder]="'Ingrese su email'" [alCambiarValor]="this.cambiaEmail.bind(this)"></form-input>
          <form-input #contrasena [texto]="'Contraseña'" [tipo]="'password'"
            [placeholder]="'Ingrese su contraseña'" [alCambiarValor]="this.cambiaContrasena.bind(this)"></form-input>


          <div type="submit" [ngClass]="{button:true, expanded:true, disabled:!validCorrecta}" (click)="clickIngresar($event)">Ingresar</div>

        </form>
        <label class="text-center lblError" *ngIf="errorEnvio">{{msjError}}</label>
      </div>
    </div>
  </div>
</div>

// Tienda_ReactJS/Login.jsx
import React from 'react';
import { Redirect } from 'react-router-dom';
import { Cell, Grid, GridContainer, Link as BtnLink } from 'react-foundation';

import FormInput from './FormInput.jsx';
import conexionBD from './conexionBD';

class Login extends React.Component {

  constructor(){
    super();
    this.state = {
      validCorrecta:false,
      errorEnvio:false,
      exitoLogin:false,
      msjError:""
    }

    this.emailIngresado = "";
    this.emailValidCorrecta = false;
    this.contrasenaIngresada = "";
    this.contrasenaValidCorrecta = false;
  }

  render(){
    if(this.state.exitoLogin){
      return(<Redirect to="/catalogo" push/>);
    }
    return(
      <div className="login">
        <div className="fondo loginFondo"/>

        <GridContainer fluid className="cubrirAltura">
          <Grid alignY="middle" className="cubrirAltura">

            <Cell small={8} medium={6} large={4} offsetOnSmall={2} offsetOnMedium={3} offsetOnLarge={4}>
              <h3 className="tituloLogin">Inicia Sesión</h3>

              <FormInput tipo="email" texto="Correo electrónico" placeholder="Ingrese su email"
                alCambiarValor={this.cambiaEmail.bind(this)}/>

              <FormInput tipo="password" texto="Contraseña" placeholder="Ingrese su contraseña"
                alCambiarValor={this.cambiaContrasena.bind(this)}/>

              <BtnLink isExpanded
                className={this.state.validCorrecta ? "":"disabled"}
                onClick={this.state.validCorrecta ? this.clickIngresar.bind(this) : null}>Ingresar
              </BtnLink>

              <label className={"text-center lblError "+(this.state.errorEnvio ? "":"hide")}>
                {this.state.msjError}</label>
            </Cell>

          </Grid>
        </GridContainer>

      </div>
    );
  }

  clickIngresar(){
    this.intentarLogin((resultado) => {
      if(resultado.exito){
        console.log("Usuario "+this.emailIngresado+" logueado");
        this.setState({
          exitoLogin:true,
          errorEnvio:false
        });
      } else {
        if(this.state.msjError == resultado.msjError){
          resultado.msjError = "*** "+resultado.msjError+" ***";
        }
        if(resultado.error){
          console.log(resultado.error);
        }
        this.setState({
          errorEnvio:true,
          msjError:resultado.msjError
        });
      }
    });
  }

  //Al modificarse el input del email
  cambiaEmail(email, esValido){
    this.emailIngresado = email;
    this.emailValidCorrecta = esValido;
    this.verificarValidarDatos();
  }

  //Al modificarse el input de la contraseña
  cambiaContrasena(contrasena, esValido){
    this.contrasenaIngresada = contrasena;
    this.contrasenaValidCorrecta = esValido;
    this.verificarValidarDatos();
  }

  //Validamos los campos del lado del cliente
  verificarValidarDatos(){
    if(!this.state.validCorrecta && this.emailValidCorrecta && this.contrasenaValidCorrecta){
      this.setState({validCorrecta:true});
    } else if(this.state.validCorrecta && (!this.emailValidCorrecta || !this.contrasenaValidCorrecta)){
      this.setState({validCorrecta:false});
    }
  }

  //Prueba a hacer login con el email y la contraseña ingresada enviando los datos al servidor.
  intentarLogin(callback){
    let email = this.emailIngresado;
    let contrasena = this.contrasenaIngresada;

    conexionBD.intentarLogin(email, contrasena, (respuesta) => {
      callback(respuesta);
    });

  }
}

export default Login;
