// Tienda_AngularJS/src/app/producto-carrito/producto-carrito.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { ConexionBDService } from '../conexion-bd.service';
import { ClienteTiendaService } from '../cliente-tienda.service';

@Component({
  selector: 'producto-carrito',
  templateUrl: './producto-carrito.component.html',
  styleUrls: ['./producto-carrito.component.css']
})
export class ProductoCarritoComponent implements OnInit {

  @Input() idProducto:string;
  @Input() cantidad:number;
  @Input() anadirSubtotal;

  producto = null;

  constructor(
    private conexionBDService:ConexionBDService,
    private clienteTiendaService:ClienteTiendaService
  ) { }

  ngOnInit() {
    //Inicializamos el componente cargando el producto y la cantidad desde el servidor
    this.cargarProducto(this.idProducto);
  }

  //--Carga este ítem del carrito obtieniendo los datos del servidor
  cargarProducto(idProducto){
    this.conexionBDService.obtenerDetalleProducto(idProducto, (respuesta)=>{
      if(respuesta.exito){
        this.producto = respuesta.producto;

        //Sumamos este subtotal al total con la función del Carrito pasada por atributo (ver carrito.component.html)
        this.anadirSubtotal(respuesta.producto.precio * this.cantidad);
      } else {
        //ERROR
        console.log("Error al conectar con el servidor: "+respuesta.msjError);
        console.log(respuesta.error);
      }
    });
  }
}

<div class="cell small-12 productoCarrito">
  <div class="grid-x grid-margin-x" *ngIf="producto != null">
    <div class="cell small-4">
      <img [src]="'assets/imagenesBase/'+producto.nombreArchivo">
    </div>
    <div class="cell small-8">
      <label class="lblProducto"><h4>{{producto.nombre}}</h4></label>
      <label class="lblProducto"><b>Cantidad: </b>{{cantidad}}</label>
      <label class="lblProducto"><b>Precio Unitario: </b>{{producto.precio}}</label>
    </div>
    <div class="cell small-12">
      <label class="lblProducto"><h5>Subtotal: ${{producto.precio * cantidad}}</h5></label>
    </div>
  </div>
</div>

// Tienda_ReactJS/ProductoCarrito.jsx
import React from 'react';
import { Cell, Grid } from 'react-foundation';

import conexionBD from './conexionBD';

class ProductoCarrito extends React.Component {

  constructor(props){
    super(props);
    this.state = {
      producto:null,
      cantidad:0
    }
    //Inicializamos el componente cargando el producto y la cantidad desde el servidor
    this.cargarProducto(props.idProducto);
  }

  render(){
    return(
      <Cell small={12} className="productoCarrito">
        {
          this.state.producto ?
          <Grid gutters="margin">
            <Cell small={4}>
              <img src={"./imagenesBase/"+this.state.producto.nombreArchivo}/>
            </Cell>
            <Cell small={8}>
              <label className="lblProducto"><h4>{this.state.producto.nombre}</h4></label>
              <label className="lblProducto"><b>Cantidad: </b>{this.state.cantidad}</label>
              <label className="lblProducto"><b>Precio Unitario: </b>${this.state.producto.precio}</label>
            </Cell>
            <Cell small={12}>
              <label className="lblProducto"><h5>Subtotal: ${this.state.producto.precio * this.state.cantidad}</h5></label>
            </Cell>
          </Grid>
          : null
        }
      </Cell>
    );
  }

  //--Carga este ítem del carrito obtieniendo los datos del servidor
  cargarProducto(idProducto){
    let respuesta = conexionBD.obtenerDetalleProducto(idProducto, (respuesta)=>{
      if(respuesta.exito){
        this.setState({producto:respuesta.producto, cantidad:this.props.cantidad});

        //Sumamos este subtotal al total con la función del Carrito pasada por props
        this.props.anadirSubtotal(respuesta.producto.precio * this.props.cantidad);
      } else {
        //ERROR
        console.log("Error al conectar con el servidor: "+respuesta.msjError);
        console.log(respuesta.error);
      }
    });
  }
}

export default ProductoCarrito;
